# Generated by Django 5.1.3 on 2024-12-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.IntegerField(blank=True, max_length=30, null=True)),
                ('User', models.IntegerField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.IntegerField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Feedback', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Offer', models.CharField(blank=True, max_length=30, null=True)),
                ('StartDate', models.CharField(blank=True, max_length=30, null=True)),
                ('EndDate', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.FileField(blank=True, max_length=30, null=True, upload_to='')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Price', models.CharField(blank=True, max_length=30, null=True)),
                ('ManufacturingDate', models.CharField(blank=True, max_length=30, null=True)),
                ('ExpiryDate', models.CharField(blank=True, max_length=30, null=True)),
                ('ProductDescreption', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Rating', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.CharField(blank=True, max_length=30, null=True)),
                ('Area', models.CharField(blank=True, max_length=30, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('Salary', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.IntegerField(blank=True, max_length=30, null=True)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
