# Generated by Django 5.1.3 on 2024-12-01 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrolleyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillTable',
        ),
        migrations.RemoveField(
            model_name='producttable',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='Username',
        ),
        migrations.AddField(
            model_name='carttable',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carttable',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carttable',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartTrolleyApp.usertable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttable',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carttable',
            name='Product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='Feedback',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartTrolleyApp.usertable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerstable',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerstable',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartTrolleyApp.producttable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerstable',
            name='StartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='ExpiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='ManufacturingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='ProductDescreption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='Rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartTrolleyApp.usertable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='Address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='Area',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='Login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartTrolleyApp.logintable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='PhoneNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='Salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartTrolleyApp.logintable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertable',
            name='PhoneNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
