# Generated by Django 5.1.3 on 2024-12-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrolleyApp', '0002_delete_billtable_remove_producttable_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttable',
            old_name='ProductDescreption',
            new_name='BrandName',
        ),
    ]
