# Generated by Django 5.1.3 on 2024-12-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrolleyApp', '0003_rename_productdescreption_producttable_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='Offer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
