# Generated by Django 5.1.3 on 2024-12-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrolleyApp', '0004_producttable_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='ExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='ManufacturingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
