# Generated by Django 5.1.3 on 2024-12-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTrolleyApp', '0005_alter_producttable_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmartTrolleyApp.producttable'),
            preserve_default=False,
        ),
    ]
